### ISSUE TITLE
Notices and errors on fresh install

### ISSUE THREAD

**Issue by gingerbeardman** [mhzawadi/docker-picocms#4]
I just brought up this container, no changes other than my own custom port number. 

I was not really knowing what to expect, but I see this:

<img width="1080" alt="Screen shot 2022-04-25 at 19 41 03" src="https://user-images.githubusercontent.com/49612/165153395-72fd414d-772a-4bd3-aa09-2cc6549e9303.png">

Any advice would be appreciated as to
- better usage
- expectations
- next steps

Thanks for making a docker container for picocms!

**Comment by mhzawadi** [comment]
Hey @gingerbeardman 
Thanks for your issue report, I have also had issues getting the site up as a fresh install.

Turns out composer was messing things up and i couldnt get a fresh install to work, even with sample content.

I have now fixed the image and new versions are on the Docker hub, please pull and retest. Also an update to the readme, but could do with feedback on that.

#5 fixes this issue

**Comment by gingerbeardman** [comment]
Thanks, it now works!

Aside: I tried to be lazy and do:

```
docker run --name picocms
  -p 8080:80
  -v /my_dir/:/var/www/html/
  -d mhzawadi/picocms
```

...but that did not work. I kind of wonder why as it feels like it should work?

Anyway, I specified multiple volumes and all is well.

Onwards!
